spring:
  data:
    mongodb:
      username: innocentcharlesudo
      password: Bn19c0248
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:dev.Innocent.notification.kafka.order.OrderConfirmation,
          paymentConfirmation:dev.Innocent.notification.kafka.payment.PaymentConfirmation;

  mail:
    host: localhost
    port: 1025
    username: innocentcharlesudo
    password: Bn19c0248
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040