services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: InnocentUdo
      POSTGRES_PASSWORD: Bn19c0248@
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=innocentcharlesudo
      - MONGO_INITDB_ROOT_PASSWORD=Bn19c0248

#  oracle:
#    container_name: oracle_db
#    image: oracleinanutshell/oracle-xe-11g
#    ports:
#      - 1521:1521
#      - 8080:8080
#    environment:
#      - ORACLE_ALLOW_REMOTE=true
#      - ORACLE_ENABLE_XDB=true
#      - ORACLE_DISABLE_ASYNCH_IO=true
#      - ORACLE_PASSWORD=Bn19c0248@

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=innocentcharlesudo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Bn19c0248
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
